# Generated by Django 3.1.4 on 2021-01-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0003_info_platform_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirements',
            name='game',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='Requirements',
        ),
    ]
