# Generated by Django 3.1.4 on 2021-01-16 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0005_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='releasee_date',
            new_name='release_date',
        ),
    ]
