# Generated by Django 3.1.4 on 2021-01-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0007_auto_20210116_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='platform',
        ),
        migrations.AddField(
            model_name='info',
            name='platform',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
