# Generated by Django 3.1.4 on 2021-01-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0008_auto_20210116_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=50)),
                ('graphics', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('directx', models.ManyToManyField(to='gamedb.Version')),
            ],
        ),
    ]
