# Generated by Django 3.1.4 on 2021-01-16 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0009_requirement_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamedb.game'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='directx',
            field=models.ManyToManyField(related_name='directxversion', to='gamedb.Version'),
        ),
    ]
