# Generated by Django 3.1.4 on 2021-01-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0010_auto_20210116_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='directx',
        ),
        migrations.AddField(
            model_name='requirement',
            name='directx',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Version',
        ),
    ]
