# Generated by Django 3.1.4 on 2021-01-16 12:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0011_auto_20210116_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphics', models.IntegerField()),
                ('story_line', models.IntegerField()),
                ('character', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('steam', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('ign', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamedb.game')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(max_length=50)),
                ('sound', models.CharField(max_length=50)),
                ('rtx_support', models.BooleanField()),
                ('game_engine', models.CharField(max_length=50)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamedb.game')),
            ],
        ),
    ]
