# Generated by Django 3.1.4 on 2021-01-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0012_detail_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
