# Generated by Django 3.1.4 on 2021-01-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0013_game_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
