# Generated by Django 3.1.4 on 2021-01-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0014_auto_20210116_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
