# Generated by Django 3.1.4 on 2021-01-16 13:30

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0015_auto_20210116_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='url',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
