# Generated by Django 3.1.4 on 2021-01-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0016_auto_20210116_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='info',
            name='platform',
        ),
        migrations.AddField(
            model_name='info',
            name='platform',
            field=models.ManyToManyField(to='gamedb.Platform'),
        ),
    ]
