# Generated by Django 3.1.4 on 2021-01-16 17:31

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0017_auto_20210116_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='url',
        ),
        migrations.AddField(
            model_name='info',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
