# Generated by Django 3.1.4 on 2021-01-16 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0018_auto_20210116_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ign',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='steam',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='cpu',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='graphics',
            field=models.CharField(max_length=150),
        ),
    ]
