# Generated by Django 3.1.4 on 2021-01-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0019_auto_20210117_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='platform',
        ),
        migrations.AddField(
            model_name='info',
            name='platform',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
